function renderRecommend(){
  document.getElementById('recommend-body').innerHTML=renderHero()+renderTopTools()+renderQuickEntries()+renderRecommendations()+renderRecentChanges();
  bindQuickEntries();
}
function renderHero(){
  const h=site.header||{};
  const stats=(h.stats||[]).map(s=>'<div><div class="hero-stat-value">'+escapeHtml(s.value)+'<span style="font-size:13px;color:var(--text-tertiary);font-weight:500;margin-left:2px;">'+escapeHtml(s.unit||'')+'</span></div><div class="hero-stat-label">'+escapeHtml(s.label)+'</div></div>').join('');
  return'<section class="hero"><div class="container"><div class="hero-inner"><div>'+
    '<span class="section-eyebrow">'+escapeHtml(h.updateDate||'')+'</span>'+
    '<h1 class="hero-title">AI 编程工具<br><span class="hero-title-accent">22 款到底选哪个？</span></h1>'+
    '<p class="hero-subtitle">'+escapeHtml(site.tagline||'')+'</p>'+
    '<p style="font-size:13px;color:var(--text-tertiary);margin-bottom:var(--space-5);margin-top:-12px;">'+escapeHtml(h.highlights||'')+'</p>'+
    '<div class="hero-actions"><a href="#browse" class="btn btn-primary btn-lg">对比所有工具</a><a href="#community" class="btn btn-secondary btn-lg">订阅周刊</a></div>'+
    '<div class="hero-stats">'+stats+'</div></div></div></section>';
}
function renderTopTools(){
  const top3=[...tools].filter(t=>t.featured).sort((a,b)=>b.rating-a.rating).slice(0,3);
  if(!top3.length)return'';
  const labels=['综合之王','开箱即用','开源最强'];
  const reasons=['编程能力、生态和灵活性的综合冠军。Claude Code 是所有 AI 编程工具的标杆。','不想折腾配置、不想学 CLI？Cursor 开箱即用，500 万用户的选择。','完全免费、高度可定制、支持任意模型。开源社区最活跃的 AI 编程工具。'];
  return'<section class="section-sm"><div class="container"><div class="section-header" style="margin-bottom:var(--space-4);"><span class="section-eyebrow">TOP PICKS</span><h2 class="section-title">不知道选哪个？先看这三款</h2><p class="section-subtitle">基于编程能力、易用性和生态的综合推荐。点击场景卡片筛选或浏览全部 22 款工具。</p></div><div class="top-pick-grid">'+top3.map((t,i)=>{const isBest=i===0;return'<div class="top-pick-card'+(isBest?' pick-best':'')+'"><div class="top-pick-label">'+labels[i]+'</div><div class="top-pick-vendor">'+escapeHtml(t.name)+'</div><div class="top-pick-plan">'+escapeHtml(t.vendor)+' · '+escapeHtml(t.type)+' · '+escapeHtml(t.pricing.split('。')[0])+'</div><div style="margin-top:var(--space-3);">'+renderStars(t.rating)+'</div><div class="top-pick-metrics"><div><div class="top-pick-metric-value">'+t.features.length+'</div><div class="top-pick-metric-label">功能数</div></div><div><div class="top-pick-metric-value">'+t.platforms.length+'</div><div class="top-pick-metric-label">平台</div></div></div><div class="top-pick-reason">'+reasons[i]+'</div><div class="top-pick-action"><a href="#browse" class="btn btn-primary btn-sm">查看详情 →</a></div></div>'}).join('')+'</div></div></section>';
}
function renderQuickEntries(){
  const entries=site.quickEntries||[];if(!entries.length)return'';
  return'<section class="section-sm"><div class="container"><div class="section-header" style="margin-bottom:var(--space-4);"><span class="section-eyebrow">SCENARIOS</span><h2 class="section-title">按你的需求来找</h2></div><div class="quick-grid">'+entries.map(q=>'<button class="quick-card" data-entry-id="'+escapeHtml(q.id)+'"><span class="quick-card-icon">'+escapeHtml(q.icon)+'</span><span class="quick-card-title">'+escapeHtml(q.title)+'</span><span class="quick-card-desc">'+escapeHtml(q.desc)+'</span></button>').join('')+'</div></div></section>';
}
function bindQuickEntries(){document.querySelectorAll('.quick-card').forEach(card=>{card.addEventListener('click',()=>{const id=card.dataset.entryId;const entry=(site.quickEntries||[]).find(q=>q.id===id);if(!entry||!entry.filter)return;location.hash='#browse?'+Object.entries(entry.filter).map(([k,v])=>k+'='+encodeURIComponent(v)).join('&')})})}
function renderRecommendations(){
  const groups=site.recommendationGroups||[];if(!groups.length)return'';const html=groups.map((group,gi)=>{const items=(group.items||[]).map(item=>{const t=tools.find(t=>t.id===item.toolId);if(!t)return'';return'<div class="reco-item"><div class="reco-item-header"><div><div class="reco-item-vendor">'+escapeHtml(t.name)+'</div><div class="reco-item-plan">'+escapeHtml(t.vendor)+' · '+escapeHtml(t.type)+'</div></div>'+renderStars(item.rating)+'</div>'+(item.verdict?'<span class="reco-item-verdict">'+escapeHtml(item.verdict)+'</span>':'')+'<p style="font-size:13px;color:var(--text-secondary);line-height:1.5;margin-bottom:var(--space-3);">'+escapeHtml(t.description)+'</p><div style="background:var(--bg-elevated);border-radius:var(--radius-md);padding:var(--space-3);margin-bottom:var(--space-3);"><strong style="color:var(--accent);font-size:11px;">💰 价格</strong><p style="font-size:13px;color:var(--text-primary);margin-top:2px;">'+escapeHtml(t.pricing)+'</p></div><ul class="reco-item-reasons" style="margin-bottom:var(--space-3);">'+(t.strengths||[]).slice(0,2).map(s=>'<li>'+escapeHtml(s)+'</li>').join('')+'</ul><div class="reco-item-footer"><span style="font-size:12px;color:var(--text-tertiary);">'+t.platforms.map(p=>escapeHtml(p)).join(' · ')+'</span><a href="'+(t.websiteUrl||'#')+'" target="_blank" rel="nofollow sponsored" class="btn btn-primary">官网 →</a></div></div>'}).join('');const header=groups.length>1?'<div style="margin-bottom:var(--space-4);"><h3 style="font-size:16px;font-weight:700;">'+escapeHtml(group.title)+'</h3>'+(group.subtitle?'<p style="font-size:13px;color:var(--text-tertiary);">'+escapeHtml(group.subtitle)+'</p>':'')+'</div>':'';return'<div style="'+(gi>0?'margin-top:var(--space-8);':'')+'">'+header+'<div class="reco-list">'+items+'</div></div>'}).join('');return'<section class="section-sm"><div class="container"><div class="section-header" style="margin-bottom:var(--space-4);"><span class="section-eyebrow">ALL RECOMMENDATIONS</span><h2 class="section-title">饭庐者说的完整推荐</h2></div>'+html+'</div></section>';
}
const KIND_LABEL={new_tool:'新工具',tool_update:'更新',article:'文章'};
function renderRecentChanges(){const now=new Date();const cutoff=new Date(now.getTime()-30*24*60*60*1000);const recent=(changes||[]).filter(c=>new Date(c.date)>=cutoff).sort((a,b)=>b.date.localeCompare(a.date));if(!recent.length)return'';const items=recent.map(c=>{const impactBadge=c.impact==='positive'?'<span class="badge badge-positive">利好</span>':c.impact==='negative'?'<span class="badge badge-negative">利空</span>':'<span class="badge">中性</span>';const kindLabel='<span class="tag">'+(KIND_LABEL[c.kind]||c.kind)+'</span>';const titleHtml=c.kind==='article'&&c.sourceUrl?'<a href="'+escapeHtml(c.sourceUrl)+'" target="_blank" rel="noopener">'+escapeHtml(c.title)+'</a>':escapeHtml(c.title);const detailAttr=c.detail&&c.detail!==c.title?' data-detail="'+escapeHtml(c.detail).replace(/"/g,'&quot;')+'"':'';return'<div class="rc-item'+(c.featured?' rc-featured':'')+'"'+detailAttr+'><span class="rc-date">'+escapeHtml(c.date.slice(5))+'</span>'+impactBadge+'<span class="rc-title">'+titleHtml+'</span>'+kindLabel+'</div>'}).join('');return'<section class="section-sm"><div class="container"><div class="section-header" style="margin-bottom:var(--space-4);"><span class="section-eyebrow">RECENT CHANGES</span><h2 class="section-title">最近动态</h2><p class="section-subtitle">最近30天AI编程工具生态的关键变动。悬停查看详情。</p></div><div class="rc-list">'+items+'</div></div></section>';}
